# Generated by Django 3.0 on 2022-11-30 05:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(default=datetime.datetime(2022, 11, 30, 10, 35, 7, 771377))),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=60, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField()),
            ],
            options={
                'verbose_name': 'Students',
                'verbose_name_plural': 'Students',
                'db_table': 'Students',
                'ordering': ('-date_added',),
            },
        ),
    ]
